Update jenkinsfile

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -6,7 +6,7 @@ pipeline {
         IMAGE_NAME = 'devops317/mynodejs-application'
         // Your GitHub repository URL
         GIT_REPO = 'https://github.com/ShahzaibInnovation/mynodejs-application.git'
-        // SonarQube URL
+        // SonarQube server URL
         SONAR_URL = "http://192.168.43.90:9000"
     }
 
@@ -32,21 +32,34 @@ pipeline {
             }
         }
 
-        stage('Static Code Analysis') {
-            environment {
-                // SonarQube URL defined
-                SONAR_URL = "http://192.168.43.90:9000"
-            }
+        stage('Install SonarScanner') {
             steps {
-                // Run SonarQube analysis
-                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
-                    sh '''
-                        sonar-scanner \
-                        -Dsonar.projectKey=my-nodejs-app \
-                        -Dsonar.sources=. \
-                        -Dsonar.host.url=${SONAR_URL} \
-                        -Dsonar.login=$SONAR_AUTH_TOKEN
-                    '''
+                // Install SonarScanner if it's not already installed
+                sh '''
+                    if ! command -v sonar-scanner &> /dev/null
+                    then
+                        echo "SonarScanner not found, installing..."
+                        wget -qO- https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip | unzip -d /opt
+                        export PATH=$PATH:/opt/sonar-scanner-4.8.0.2856-linux/bin
+                    else
+                        echo "SonarScanner already installed"
+                    fi
+                '''
+            }
+        }
+
+        stage('Static Code Analysis (SonarQube)') {
+            steps {
+                script {
+                    withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
+                        sh '''
+                            sonar-scanner \
+                            -Dsonar.projectKey=my-nodejs-app \
+                            -Dsonar.sources=. \
+                            -Dsonar.host.url=${SONAR_URL} \
+                            -Dsonar.login=$SONAR_AUTH_TOKEN
+                        '''
+                    }
                 }
             }
         }
@@ -72,7 +85,7 @@ pipeline {
                 // Use Docker Hub credentials to log in and push the image
                 script {
                     withCredentials([usernamePassword(credentialsId: 'docker-cred', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PWD')]) {
-                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
+                        sh 'echo $DOCKER_PWD | docker login -u $DOCKER_USERNAME --password-stdin'
                         sh "docker push ${IMAGE_NAME}:${BUILD_NUMBER}"
                     }
                 }
